USE InstitutoTich
SET IDENTITY_INSERT [dbo].[Estados] ON 

INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (1, N'Aguascalientes')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (2, N'Baja California')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (3, N'Baja California Sur')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (4, N'Campeche')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (5, N'Chihuahua')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (6, N'Chiapas')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (7, N'Coahuila')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (8, N'Colima')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (9, N'Durango')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (10, N'Guanajuato')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (11, N'Guerrero')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (12, N'Hidalgo')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (13, N'Jalisco')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (14, N'México')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (15, N'Michoacán')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (16, N'Morelos')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (17, N'Nayarit')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (18, N'Nuevo León')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (19, N'Oaxaca')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (20, N'Puebla')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (21, N'Querétaro')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (22, N'Quintana Roo')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (23, N'San Luis Potosí')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (24, N'Sinaloa')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (25, N'Sonora')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (26, N'Tabasco')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (27, N'Tamaulipas')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (28, N'Tlaxcala')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (29, N'Veracruz')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (30, N'Yucatán')
INSERT [dbo].[Estados] ([idEstados], [nombre]) VALUES (31, N'Zacatecas')

SET IDENTITY_INSERT [dbo].[Estados] OFF
